default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: system_pdv_development

test:
  <<: *default
  database: system_pdv_test

production:
  primary: &primary_production
    <<: *default
    database: system_pdv_production
    username: system_pdv
    password: <%= ENV["SYSTEM_PDV_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: system_pdv_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: system_pdv_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: system_pdv_production_cable
    migrations_paths: db/cable_migrate
